package project;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;


public class Purchase {

    public static void normalWay(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }


    public static void existAddress(WebDriver driver){
        Cart.summer(driver);
        driver.get("https://www.addax.com.tr/?gad_source=1&gclid=EAIaIQobChMI5ZXk1bOrhgMVeEFBAh3KUwvYEAAYASAAEgLKvvD_BwE");
        Addax.pause(3000);
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        Addax.pause(3000);
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//tbody/tr[1]/td[3]/label[1]/span[1]")).click();
        Addax.pause(1000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }


    public static void noName(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }


    public static void noLastname(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }


    public static void noDetailAddress(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }

    public static void noCity(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }

    public static void noTown(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }

    public static void noMah(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }


    public static void noPhone(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }

    public static void noCredCardNo(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }


    public static void noMonth(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }
    public static void wrongCity(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("Ankara");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }

    public static void wrongTown(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Kuşadası");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }

    public static void wrongMah(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kadınlar mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }
    public static void wrongPhone(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("05385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }


    public static void notCompCity(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmi");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();
    }


    public static void notCompTown(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Borno");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();
    }

    public static void notCompMah(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();
    }

    public static void notCompPhone(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("53856760");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();
    }

    public static void notCompCredCard(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();
    }

    public static void notCompMonth(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("0");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();
    }
    public static void addedItem(WebDriver driver){
        Cart.summer(driver);
        Addax.pause(3000);
        driver.get("https://www.addax.com.tr/");
        driver.findElement(By.cssSelector("span[class='RightButtonText BasketCountText'] span[class='HeaderText']")).click();
        Addax.pause(3000);
        driver.findElement(By.cssSelector("#PayNow")).click();
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(4000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='UserName']")).sendKeys("ayvaogluayva@gmail.com");
        Addax.pause(3000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).click();
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//input[@id='Password']")).sendKeys("ayvaAyva1.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//form[@class='form-horizontal UyeGiris']//button[@id='LoginButton']")).click();
        Addax.pause(2000);
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//div[@class='btn AddAdress AdresPopup']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='FirstName']")).click();
        driver.findElement(By.xpath("//input[@id='FirstName']")).sendKeys("Ayva");
        Addax.pause(3000);
        driver.findElement(By.xpath("//input[@id='LastName']")).click();
        driver.findElement(By.xpath("//input[@id='LastName']")).sendKeys("Ayvaoğlu");
        Addax.pause(2000);
        driver.findElement(By.xpath("//textarea[@id='Detail']")).click();
        driver.findElement(By.xpath("//textarea[@id='Detail']")).sendKeys("Ayva mah., Ayva Sitesi, Ayva sk.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='CityID']")).click();
        driver.findElement(By.xpath("//select[@id='CityID']")).sendKeys("İzmir");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='CityID']")).submit();
        driver.findElement(By.xpath("//select[@id='TownID']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@id='TownID']")).sendKeys("Bornova");
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='QuarterID']")).click();
        driver.findElement(By.xpath("//select[@id='QuarterID']")).sendKeys("Kazımdirik mah.");
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@id='TownID']")).submit();
        driver.findElement(By.xpath("//input[@id='Phone2']")).click();
        driver.findElement(By.xpath("//input[@id='Phone2']")).sendKeys("5385676045");
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        Addax.pause(3000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).click();
        driver.findElement(By.xpath("//input[@id='CardNumbers']")).sendKeys("1111111111111111");
        Addax.pause(4000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).click();
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).sendKeys("06");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresMonth']")).submit();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).sendKeys("2026");
        Addax.pause(3000);
        driver.findElement(By.xpath("//select[@class='form-control ExpiresYear']")).submit();
        driver.findElement(By.xpath("//input[@name='cvcForm']")).click();
        Addax.pause(2000);
        driver.findElement(By.xpath("//input[@name='cvcForm']")).sendKeys("111");
        Addax.pause(2000);
        driver.findElement(By.xpath("//button[@id='nextbtn']")).click();
        Addax.pause(5000);
        driver.quit();

    }


    public static void nothing(WebDriver driver){
        driver.findElement(By.cssSelector("span[class='RightButtonText BasketCountText'] span[class='HeaderText']")).click();
        driver.findElement(By.cssSelector("#PayNow")).click();
        driver.findElement(By.cssSelector("#nextbtn")).click();
        Addax.pause(5000);
        driver.quit();
    }


    public static void withoutItemWithAddress(WebDriver driver){
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("div[id='Steps'] button[data-next='adres'] span")).click();
        Addax.pause(5000);
        driver.quit();
    }

    public static void withoutItemPurchase(WebDriver driver){
        driver.get("https://www.addax.com.tr/tr/p/CheckOut/sepet");
        driver.findElement(By.cssSelector("button[data-next='odeme'] span")).click();
        Addax.pause(5000);
        driver.quit();
    }
}
